stages:
  - build

build:
  stage: build
  script:
    - $Env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
    - 'nuget restore' 
    - 'msbuild /property:Configuration=Release' 
  artifacts:
    paths:
      - 'TypeCsv\bin\Release\TypeCsv.exe'
  release:
    assets:
      - name: 'TypeCsv.exe'
        path: 'TypeCsv\bin\Release\TypeCsv.exe'
  tags : [windows]
