stages:
  - build

build:
  stage: build
  script:
    - $Env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
    - 'nuget restore' 
    - 'msbuild /property:Configuration=Release' 
  artifacts:
    paths:
      - 'TypeCsv\bin\Release\TypeCsv.exe'
  tags : [windows]

release:
  stage: release
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"Executable file\",\"url\":\"https://gitlab.com/patleahy/TypeCsv/-/jobs/artifacts/master/file/TypeCsv/bin/Release/TypeCsv.exe?job=build\"}"
  rules:
    - if: $CI_COMMIT_TAG
